import { FlagEmojiPolyfill } from "@/components/common/flag-emoji-polyfill";
import { Navbar } from "@/components/layout/navbar";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

// Applies the saved (or system) theme before first paint to avoid a flash.
const THEME_SCRIPT = `(function(){try{var t=localStorage.getItem('theme');var d=t?t==='dark':window.matchMedia('(prefers-color-scheme: dark)').matches;if(d)document.documentElement.classList.add('dark');}catch(e){}})();`;

const RootLayout = ({ children }: Props) => (
  <ClerkProvider>
    <html lang="en" suppressHydrationWarning className="h-full antialiased">
      <body className="min-h-full flex flex-col font-sans">
        <script dangerouslySetInnerHTML={{ __html: THEME_SCRIPT }} />
        <FlagEmojiPolyfill />
        <Navbar />
        {children}
      </body>
    </html>
  </ClerkProvider>
);

export default RootLayout;
