import type { Metadata } from "next";
import type { ReactNode } from "react";
import { SalesAssistantWidget } from "@/components/assistant/sales-assistant-widget";
import "./globals.css";

type RootLayoutProps = Readonly<{
  children: ReactNode;
}>;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: RootLayoutProps) => (
  <html lang="en" className="h-full antialiased">
    <body className="min-h-full flex flex-col bg-page text-ink font-sans">
      {children}
      <SalesAssistantWidget />
    </body>
  </html>
);

export default RootLayout;
