import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

const RootLayout = ({ children }: Props) => (
  <html lang="en" className="h-full antialiased">
    <body className="min-h-full flex flex-col font-sans">{children}</body>
  </html>
);

export default RootLayout;
